enable-beta-ecosystems: true
version: 2

updates:
  - package-ecosystem: "uv" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      timezone: Asia/Tokyo
      time: "06:00"
    target-branch: main
    reviewers:
      - "yuubinnkyoku"
